### ISSUE TITLE
ImportError: cannot import name 'nonseparable' from 'pilgram2.css.blending.nonseparable'

### ISSUE THREAD

**Issue by amirho3einsedaghati** [mgineer85/pilgram2#34]
Hi, could you please add the nonseparable module to the init file? Currently, it is not importable from outside the package.

<pre>
from pilgram2.css.blending.nonseparable import nonseparable

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[27], line 1
----> 1 from pilgram2.css.blending.nonseparable import nonseparable

ImportError: cannot import name 'nonseparable' from 'pilgram2.css.blending.nonseparable' (/home/amir/anaconda3/lib/python3.10/site-packages/pilgram2/css/blending/nonseparable.py)
</pre>

Best Regards

**Comment by mgineer85** [comment]
Pls have a look in the file. There is no function called nonseparable in it.

**Comment by amirho3einsedaghati** [comment]
Yeah, that's right. it seems it is an internal module. Thank you for your help.

Best Regards @mgineer85
