### ISSUE TITLE
percentage value effect filter like on instagram

### ISSUE THREAD

**Issue by sugizo** [mgineer85/pilgram2#35]
nice to have percentage value effect filter like on instagram
![image](https://github.com/mgineer85/pilgram2/assets/2418295/258b058b-2479-4e82-b00c-c816fff8e2ee)

**e.g.** 
`pilgram2.juno(im, 0.22).save('juno.jpg') # 22 % like image above` 
or
`pilgram2.css.contrast(im, 0.12).save('contrast.jpg') # 12 %`

best regards

**Comment by mgineer85** [comment]
Yes, would be nice. Would be great if you send a pull request implementing that :)
